spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.main.allow-bean-definition-overriding=true

jwt.secret=02c477941249bfd9b6639683ae9ed1a2e8d5cb08b2ec8d96f9c83d1434613bb5
jwt.expiration=86400000